# Generated by Django 5.1.3 on 2024-12-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_todo_duedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='duedate',
            new_name='due_date',
        ),
    ]
